# Generated by Django 5.0.10 on 2025-03-26 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="product",
            table="product",
        ),
    ]
