# Generated by Django 5.0.10 on 2025-03-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0003_category_supplier_product_category_product_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, upload_to="product_images/"),
        ),
    ]
