# Generated by Django 5.0.11 on 2025-02-03 17:13

from django.db import migrations


def add_books_data(apps, schema_editor):
    Books = apps.get_model('UserAccount', 'Books')
    UserAccount = apps.get_model('UserAccount', 'UserAccount')
    user = UserAccount.objects.first()  # Replace with the appropriate user

    if not user:
        print("No user found. Please ensure there is at least one user in the UserAccount model.")
        return

    books_data = [
        {
            "title": "Sample Book 1",
            "author": "Author 1",
            "description": "Description 1",
            "publication_date": "2023-01-01",
            "isbn": "1234567890123",
            "price": 19.99,
            "user": user,
        },
        {
            "title": "Sample Book 2",
            "author": "Author 2",
            "description": "Description 2",
            "publication_date": "2023-02-01",
            "isbn": "1234567890124",
            "price": 29.99,
            "user": user,
        },
    ]

    for book_data in books_data:
        Books.objects.create(**book_data)
        print(f"Added book: {book_data['title']}")


class Migration(migrations.Migration):

    dependencies = [
        ("UserAccount", "0002_books"),
    ]

    operations = [
        migrations.RunPython(add_books_data),
    ]
