# Generated by Django 5.0.10 on 2025-03-26 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UserAccount", "0002_books"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Books",
        ),
    ]
